name: Build and Release Extension

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(grep '"version"' manifest.json | cut -d'"' -f4)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extension version: $VERSION"
        
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Build extension package
      run: |
        chmod +x scripts/build-webstore.sh
        scripts/build-webstore.sh
        
        echo "Build complete!"
        ls -la builds/
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: "builds/grocery-autoclip-v${{ steps.version.outputs.version }}-webstore.zip"
        
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## Safeway Coupon Clipper Extension v${{ steps.version.outputs.version }}
          
          Automatically clips available Safeway digital coupons.
          
          ## Installation
          1. Download the zip file below
          2. Extract it to a folder
          3. Open Chrome and go to chrome://extensions/
          4. Enable "Developer mode" in the top right
          5. Click "Load unpacked" and select the extracted folder
          
        files: |
          builds/grocery-autoclip-v${{ steps.version.outputs.version }}-webstore.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 